### ISSUE TITLE
pipenv install development version

### ISSUE THREAD

**Issue by sladkovm** [GoldenCheetah/OpenData#8] opened 2018-12-06 11:09 UTC
`pipenv install -e git+https://github.com/GoldenCheetah/OpenData.git#egg=opendata` does not work 

Will add the error code seen on Mac OS later...

**Comment by sladkovm** [comment] 2018-12-06 13:51
```
536 sladkovm:gc-opendata$ pip install -e git+https://github.com/GoldenCheetah/OpenData.git/#egg=opendata&subdirectory=opendata-python
[1] 78200

537 sladkovm:gc-opendata$ Obtaining opendata from git+https://github.com/GoldenCheetah/OpenData.git/#egg=opendata
  Cloning https://github.com/GoldenCheetah/OpenData.git/ to ./src/opendata
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/anaconda3/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/sladkovm/Dropbox/Projects/gc-opendata/src/opendata/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/sladkovm/Dropbox/Projects/gc-opendata/src/opendata/

[1]+  Exit 1                  pip install -e git+https://github.com/GoldenCheetah/OpenData.git/#egg=opendata

538 sladkovm:gc-opendata$ ls src/opendata/
README.md	examples	opendata-python
```

somehow I need to tell pip to look for setup-file in the subdirectory opendata-python

**Comment by sladkovm** [comment] 2018-12-06 14:24
Interesting that:

`pip install git+https://github.com/GoldenCheetah/OpenData.git#subdirectory=opendata-python`

works fine, but with `-e` flag the `#egg=<package_name>` directive is required and both pip and pipenv do fail... could be a pip problem

**Comment by AartGoossens** [comment] 2018-12-10 10:37
I think it has something to do with that the Python code is actually in a sub-directory of this git repo as you already suggested and I am not sure if we can do something about that other than using the `subdirectory` in the pip-command.

A way around this issue is to build and install locally:
- Clone repo
- `cd` into the opendata-python directory of the repo
- Run `make build` (requires pipenv to be installed) or run `python setup.py sdist bdist_wheel`
- A file `dist/goldencheetah_opendata-<vresion number>-py3-none-any.whl` should be created
- Then from anywhere on your pc: `pip install <path to .whl file>`

**Comment by AartGoossens** [comment] 2018-12-10 14:50
I can confirm that specifying the subdirectory is indeed necessary and the following 2 commands work for me:
- `pipenv install -e git+https://github.com/GoldenCheetah/OpenData.git#egg=opendata\&subdirectory=opendata-python`
- `pipenv install git+https://github.com/GoldenCheetah/OpenData.git#subdirectory=opendata-python`

In conclusion: Because the Python library lives in a subdirectory in this repository it is always necessary to specify this subdirectory when installing from git.
@sladkovm Can you double check my conclusion and close this issue if you agree?

**Comment by sladkovm** [comment] 2018-12-10 19:18
Great! The first command works, apparently the `\&` must be escaped.

The second one, without egg, does not work, and probably should not.

```
(pipenv) bash-3.2$ pipenv install git+https://github.com/GoldenCheetah/OpenData.git#subdirectory=opendata-python
Installing git+https://github.com/GoldenCheetah/OpenData.git#subdirectory=opendata-python…
WARNING: pipenv requires an #egg fragment for version controlled dependencies. Please install remote dependency in the form git+https://github.com/GoldenCheetah/OpenData.git#egg=<package-name>.
✘ Installation Failed
```

**Comment by sladkovm** [comment] 2018-12-10 19:20
solved

**Comment by AartGoossens** [comment] 2018-12-11 08:09
The second command indeed fails for me too. Apparently I copy-pasted something else, sorry about that.

Closing this issue as it's solved.

**Closed as completed by AartGoossens** 2018-12-11 08:09 UTC
Labels: bug
